### PR TITLE
Changes to allow for a magic index replacement variable

### PR DESCRIPTION
**Pull request by montulli**
I wanted to use nested_form_fields with rails3-jquery-autocomplete which uses a "data" attribute on the autocomplete field to specify which hidden field to store the selected autocompleted id.   Since the id of the hidden field changes based on the number of elements it doesn't work.    By adding a magic replacement string I am able to accurately target the hidden field and autocomplete will now work with nested_form_fields.

I'm happy to implement something different if you have a better idea on how to solve this problem.

BTW- rails4-autocomplete appears to require the same functionality.

### CODE REVIEW

**Comment by ncri** [comment]
If you simply need the index in the nested_fields block, you can already do this like this:

    = f.nested_fields_for :items, @model.items do |f_items|
        = @model.items.index(f_items.object) || f.send(:index_placeholder, 'items')

Using `send` is a bit hackish here. You could also use the string directly: `"__model_items_index__"` in case model has class `Model`.

**Comment by montulli** [comment]
I originally tried using "__model_items_index__", but there was a problem with that.   The string was only replaced when adding a new element via the add_nested_fields_link link.   For any has_many relations that already existed the string would not be replaced.    Will "f.send(:index_placeholder, 'items')" work in all cases?

Also, wouldn't you rather have a well designed feature for this use case rather than "f.send"?

**Comment by ncri** [comment]
Yes, thats why I added `@model.items.index(f_items.object)`, without it, it wouldn't work for existing items. We could simply make index_placeholder public and you could put `@model.items.index(f_items.object) || f.send(:index_placeholder, 'items')` in a helper. I'd prefer that over adding more code to nested fields for this not so common case. Would that be okay for you?

**Comment by montulli** [comment]
Sounds good to me.   It should also be added to the documentation.   I agree it isn't terribly common, but it is very useful functionality when needed.

Thanks.

**Comment by ncri** [comment]
Changed my mind and merged this :) Your code changes are rather small and the functionality is useful to have directly supported, I agree. Will release a new version.

**Comment by ncri** [comment]
Released 0.7.7.

**Comment by ncri** [comment]
And thanks for your contribution. ;-)

**Pull request merged**
