### PR TITLE
Ability to disable nested fields wrapping

### PR DESCRIPTION
**Pull request by ertaquo**
Use wrapper_tag: nil in options to disable nested fields wrapping.

Sorry for two different features in one pull request, but i'm newbie in such pull requests :)

### CODE REVIEW

**Comment by ncri** [comment]
The wrapper cannot be removed, it's essential to the gems functioning... what is your use case?

**Comment by ertaquo** [comment]
My fields are inside <ul />, so <fieldset /> instead of <li /> cause errors. Anyway, gem works perfect without wrapper - there was only one problem with add_nested_fields_link (wrong index for new fields), but i fixed it too.

**Comment by ertaquo** [comment]
Sorry for troubling, it need review :-\

**Comment by ncri** [comment]
Ah, okay, maybe it is possible to make it possible not use the wrapper. However, I doubt it. ;-) Also the tests were failing. Question is, why would that be needed?

**Pull request closed without merging**
